### ISSUE TITLE
collection from softflow fails

### ISSUE THREAD

**Issue by momo7** [bitkeks/python-netflow-v9-softflowd#6] opened 2018-11-06 13:34 UTC
Hi,

after installing and running the collector, I get the following error:

Exception happened during processing of request from (, 55757)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "main.py", line 72, in handle
    export = ExportPacket(data, self.TEMPLATES)
  File "/root/netflow/src/netflow/collector_v9.py", line 312, in __init__
    tfs = TemplateFlowSet(data[offset:])
  File "/root/netflow/src/netflow/collector_v9.py", line 266, in __init__
    field_type, field_length = struct.unpack('!HH', data[offset:offset+4])
struct.error: unpack requires a bytes object of length 4

Any idea what could be the issue?

**Comment by bitkeks** [comment] 2018-11-28 15:11
Hi, thanks for your report!
The cause might be a wrongly formatted export packet. Could you give some more information what exporter you use? 

If you wish to debug it yourself, you can capture your traffic with `tcpdump -w <pcap-file>` and read this capture with `softflowd -r <pcap-file>`. softflowd then generates TCP flow exports like it would in a live session. The export can then be sent to the collector.

**Comment by bitkeks** [comment] 2019-10-31 17:08
Closing since this issue is nearly a year old.

**Closed by bitkeks** 2019-10-31 17:08 UTC
Labels: templates/struct
